name: Update DIP21 Daten

on:
  # schedule:
  #   - cron: "0 5 * * *"
  [push] # do it on push for testing

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - continue-on-error: false
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install

      - name: Scrape Data
        run: yarn dev --html -s 10 --periods 19 --operationtypes 100
        env:
          SCRAPER_USER_AGEND: UpdateGithubData-(github.com/bundestag/dip21-daten)
